#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

libs-$(CONFIG_LIB_MUSL_C) += libmuslc-updated
libmuslc-updated: libs/libmuslc-updated/Makefile common

libs/libmuslc-updated/Makefile: | libs/libmuslc-updated/sos.patch
	curl -L https://github.com/seL4/musllibc/archive/b5c66eef4a8bb274d7a4b9b5b82bce412224dbf9.tar.gz | \
		tar xzf - -C libs/libmuslc-updated --exclude="*/Kbuild" --strip-components=1
	(cd libs/libmuslc-updated && patch -mp1 < sos.patch)
	grep -vF '#include <syscall_sel4.h>' libs/libmuslc/arch_include/arm/arch/syscall_stubs_sel4.h \
		> libs/libmuslc-updated/arch/arm_sel4/syscall_stubs_sel4.h
